### PR TITLE
Vm extension fix

### PR DESCRIPTION
**Pull request by mccbryan3**
Updated some of the TF files to reflect protected data. 
Refactored the bootstrap script
Added a generic script for install.sh based on the generalized script by Simon

### CODE REVIEW

**Comment by redhatrises** [comment]
I think we should drop `start-falcon-bootstrap.sh`. I don't think a bash script to run a bash script makes sense.

**Comment by mccbryan3** [comment]
> I think we should drop `start-falcon-bootstrap.sh`. I don't think a bash script to run a bash script makes sense.

I agree in the way that it is a little kludgey. However this fixes the current issue of not working at all without too much refactoring of the process. I was intending to work through a central deployment script in the next iteration.

**Comment by mccbryan3** [comment]
> I think we should drop `start-falcon-bootstrap.sh`. I don't think a bash script to run a bash script makes sense.

Done

**Review by jhseceng — APPROVED** [review]
Thanks for removing those additional bash scripts.

**Pull request merged**
